### ISSUE TITLE
Adyen payment gateway integration error 401.(The remote server returned an error: (401) Unauthorized.)

### ISSUE THREAD

**Issue by mayurTest** [Adyen/adyen-dotnet-api-library#12] opened 2018-06-13 10:34 UTC
Hi guys!

I am trying to implement the adyen api(C#.net) into my project and I am encountering the following issue:

An exception of type 'System.Net.WebException' occurred in AdyenPaymentGatewaySample.dll but was not handled in user code Additional information: The remote server returned an error: (401) Unauthorized.

Here is a code sample of the callback file:

var config = new Config();
config.MerchantAccount = "MyMerchantAccountName";
config.Password = "mypassword";
config.Username = "test";
config.Endpoint = "https://pal-test.adyen.com/pal/servlet/Payment/v30";
config.ApplicationName = "MyServername";
config.Environment = Test;
config.SkinCode = "7A26B737";//test
config.HmacKey = "7A26B737AN79CSpV87A7A26B737AN79CSpV87A7A26B737AN79CSpV87A";//test

        var client = new Client(config);
        var payment = new Payment(client);
        var paymentRequest = new PaymentRequest
        {
            MerchantAccount = "MyMerchantAccountName",
            Amount = new Amount("CAD", 5),
            Card = new Card(Number: "4111111111111111", ExpiryMonth: "08", ExpiryYear: "2018", Cvc: "737", HolderName: "John Smith"),
            Reference = "Merchant reference",
            AdditionalData = new Dictionary<string, string>()
        };

        var paymentResult = payment.Authorise(paymentRequest);
        return paymentResult;

Thanks in advance,

**Comment by AlexandrosMor** [comment] 2018-06-18 13:17
Hello @mayurTest,
The error 401 generally means the request lacks valid authentication credentials. Can you please check if the username and password are correct? 

kind regards,
Alexandros Moraitis

**Comment by AlexandrosMor** [comment] 2018-06-28 09:45
Hello @mayurTest,

Did the explanation helped? If you found the cause of the issue then we can close it. Please let us know.
kind regards,
Alexandros Moraitis

**Closed** 2018-07-24 13:59 UTC

**Comment by sharpblades** [comment] 2018-08-28 11:07
have same problem (401 error) try all variations of authentication credentials and still nothing

**Comment by tutunciyan** [comment] 2018-11-22 10:37
Issue is the constructor in Client accepting Config parameter. While other constructors are internally calling SetEnvironment(), this constructor does not. So, call the client.SetEnvironment(Environment.Test) method yourself.
