### ISSUE TITLE
Error: The 'Expect' header must be modified using the appropriate property or method. 

### ISSUE THREAD

**Issue by StanMarian** [Adyen/adyen-dotnet-api-library#31] opened 2018-10-24 06:55 UTC
Hello,

I'm getting the error from title when executing `payment.Authorise(paymentRequest);` and I believe it comes from this line.

https://github.com/Adyen/adyen-dotnet-api-library/blob/63eda4a1a379a2605d3f9247e128edd632013041/Adyen.EcommLibrary/HttpClient/HttpURLConnectionClient.cs#L132

I think it has to be `req.Expect = "100-continue";` (https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.expect?view=netcore-2.0)

Thank you.

**Comment by AlexandrosMor** [comment] 2018-10-24 11:58
Hello @StanMarian,

Would you like to post the exception message? 

Thank you !

**Comment by StanMarian** [comment] 2018-10-25 09:29
This is it:
`[10/25/2018 9:25:31 AM] mscorlib: Exception while executing function: AdyenTest. Adyen.EcommLibrary: The 'Expect' header must be modified using the appropriate property or method.
[10/25/2018 9:25:31 AM] Parameter name: name.`

**Comment by tutunciyan** [comment] 2018-11-21 14:00
Hi,

I have this same issue. I played around with the code base and the only solution I can think of for now is to have some platform depended code like this:

`#if NETSTANDARD`
`httpWebRequest.Headers.Add("Expect", "100-continue");`
`#else`
`httpWebRequest.ServicePoint.Expect100Continue = true;`
`#endif``

Can you guys remove this whole line or adapt something similar as above?

**Comment by AlexandrosMor** [comment] 2019-01-09 10:13
Hello @tutunciyan,

We will check it and update the library as soon as possible,

Kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment] 2019-01-17 15:09
Hey @tutunciyan @vad873 

We removed the expect header. Is it possible to check if everything works for you ? 
https://github.com/Adyen/adyen-dotnet-api-library/pull/47
Thank you in advance,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment] 2019-01-22 09:42
Hello all, 

We have a new release of .net library 1.1.5. It solves the issue. 
If you require any further information, feel free to contact us.  

Thank you in advance,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment] 2019-01-28 09:14
Hello all, 

The issue is fixed for version 1.1.5. We are closing this issue and if there is another or similar issue please open a new issue to investigate further.

Kind regards,
Alexandros
Adyen

**Closed by AlexandrosMor** 2019-01-28 09:14 UTC
