### ISSUE TITLE
Display notification model not being properly created

### ISSUE THREAD

**Issue by racashmoney** [Adyen/adyen-dotnet-api-library#466] opened 2021-06-23 15:26 UTC
**Describe the bug**
On my notifications webhook api, we're expecting a display notification to come in, thus we're using the SaleToPOIRequest model to capture that request. However when capturing it, it appears the model's properties are null. I even tried to create a class wrapper around it that had SaleToPOIRequest as a property but was still facing the same issue. I even tried SaleToPOIResponse and SaleToPOIMessage, but that didn't help either. 

Here is my code:
![image](https://user-images.githubusercontent.com/9951078/123123627-976aff80-d40c-11eb-8584-b8c33be89231.png)

Here is the Postman request (I'm using the sample json found on the Adyen documentation for display notifications)
![image](https://user-images.githubusercontent.com/9951078/123124021-ee70d480-d40c-11eb-95e1-9db95205fc84.png)

Here is what the object is showing with null properties.
![image](https://user-images.githubusercontent.com/9951078/123124126-07798580-d40d-11eb-93bc-637aa655d352.png)

**Expected behavior**
Expecting a display notification model to be filled out with the incoming json from Adyen. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**
This notifications api will be a webhook entered into Adyen for display notifications. 

Am I doing this correctly?

**Comment by AlexandrosMor** [comment] 2021-07-01 06:57
Hello @racashmoney,

Thank you for raising that issue, so there is a webhook to receive notifications but the notification that arrives is null even from postman. I see here that there is not library involved in this flow so far as the library provides the models. If you try with a dummy or another object is it the same result ? 

 regards
Alexandros
Adyen

**Comment by AlexandrosMor** [comment] 2021-08-04 18:05
Hello @racashmoney,

I will close this ticket as the issue is most likely on the application side and there is some time without answer. Feel free to open a new issue if you have more question for us or contact our support team.

kinds regards
Alexandros
Adyen

**Closed by AlexandrosMor** 2021-08-04 18:05 UTC
