### ISSUE TITLE
Missing Fraud Result

### ISSUE THREAD

**Issue by PrettyPrimate** [Adyen/adyen-dotnet-api-library#440] opened 2021-05-21 15:09 UTC
The following payment has a risk score of 50 but this isn't returned in the response. This was working in the previous version.

![image](https://user-images.githubusercontent.com/6606158/119158891-9c741200-ba4e-11eb-8b9b-400b371593c2.png)

```json
{
   "AdyenPaymentResponse":{
      "resultCode":"Authorised",
      "additionalData":{
         "liabilityShift":"true",
         "authCode":"070275",
         "avsResult":"4 AVS not supported for this card type",
         "fraudResultType":"AMBER",
         "riskProfile":"Richemont",
         "fraudManualReview":"true",
         "threeDOffered":"true",
         "eci":"05",
         "threeDSVersion":"2.1.0",
         "authorisedAmountValue":"78000",
         "cvcResult":"1 Matches",
         "cavv":"QURZRU4gM0RTMiBURVNUIENBVlY=",
         "checkoutThreeD.selectedBrand":"visa",
         "authorisedAmountCurrency":"EUR",
         "dsTransID":"8eab1993-7fdd-4e64-9269-76738550f24c",
         "recurringProcessingModel":"Subscription",
         "threeDAuthenticated":"true",
         "checkoutThreeD.merchantReference":"850299",
         "paymentMethod":"visa",
         "paymentMethodVariant":"visacredit"
      },
      "pspReference":"853620899639715A",
      "refusalReasonCode":"0"
   }
}```

**Comment by AlexandrosMor** [comment] 2021-06-02 11:01
Hello @PrettyPrimate,

The library only parses the json messages so if the Fraud Result is missing from the json response the issue is in the merchant account configuration in the customer area. You can contact support team to help you further

kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment] 2021-06-07 06:40
Hello @PrettyPrimate,

I hope you are doing well. Do you have any updates about this matter?
kind regards,
Alexandros
Adyen

**Comment by AlexandrosMor** [comment] 2021-06-21 09:16
Hello @PrettyPrimate,

I will close this issue. If you have more questions please fill free to open a new issue. 

kind regards
Alexandros
Adyen

**Closed by AlexandrosMor** 2021-06-21 09:16 UTC
