### ISSUE TITLE
Errors on Windows 8.1 and Server 2012 platforms

### ISSUE THREAD

**Issue by CatCode91** [Adyen/adyen-dotnet-api-library#533] opened 2021-12-09 07:44 UTC
Hi, team! Could you please help us to solve problem.
We built our project using your API library version of 8.0.1 for .NET Standart. But when we run transactions on our environments (Windows 8.1 or Server 2012) request method of Adyen generates error:

_Die Datei oder Assembly "System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden._

We tried to build the same project on Windows 10 machine - it works good.

I found somewhere in the google, that this lybrary of Microsoft has some problems with vesions. For solving, we downgrading Adyen library to version of 5.0.0. Now it works correct, but maybe it possible to change something for using latest version of your API library on our environments.

**Comment by AlexandrosMor** [comment] 2021-12-09 11:02
Hello @CatCode91,

Do you have the same version .net version between  Windows 8.1 and Windows 10? Might be that the issue is that based on the .net version. Could you check this [matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)? 

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment] 2021-12-30 13:52
Hello @CatCode91,

We are going to close this issue and if you have a new one please open another issue. For now we can assume that this issue is not on the library side as it works for you on windows 10

kind regards,
Alexandros

**Closed by AlexandrosMor** 2021-12-30 13:52 UTC
