### ISSUE TITLE
Adding a restricted header causes an exception

### ISSUE THREAD

**Issue by devilishgoat-mirum** [Adyen/adyen-dotnet-api-library#4] opened 2018-02-07 14:17 UTC
When we tried to use this library we recieved errors when calling the HttpUrlConnectionClient.Request method.

The error is thrown as the code is trying to set the paramenter User-Agent in the call on line 99 but I think you should set the user agent by calling HttpWebRequest .UserAgent

Issue is mentioned [here](https://stackoverflow.com/questions/239725/cannot-set-some-http-headers-when-using-system-net-webrequest)

**Comment by AlexandrosMor** [comment] 2018-02-19 08:16
Hello @devilishgoat-mirum,

The issue is solved with the 1.0.3 release. If you test it and it is working fine for you please close the issue :)

Thank you in advance,

**Comment by AlexandrosMor** [comment] 2018-04-26 14:57
Hello @devilishgoat-mirum 
We already release 1.0.4. You can update it from nuget.
Install-Package Adyen.EcommLibrary -Version 1.0.4 
kind regards,
Alexandros

**Closed by AlexandrosMor** 2018-04-26 14:57 UTC
